safety_node_old:
  ros__parameters:
    ttc_pb1 : 0.7
    ttc_pb2 : 1.6
    ttc_fb : 0.2
    pb1_speed_mult : 0.4
    pb2_speed_mult : 0.2
    front_half_angle : 0.40
    distance_threshold : 0.35
    timer_period_seconds : 0.1
